name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      id: build_jdk
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: build distribution
      run: |
        ./mvnw --version
        echo $PATH
        ./mvnw -B -fae clean install
